'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';

import '@p/common-styles/common.css';
import '@i/index';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { i18n } = useTranslation();

  useEffect(() => {
    // use the correct language
    i18n.changeLanguage('cn');
  }, [i18n]);
  return (
    <html lang="cn">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
